# Generated by Django 4.1.2 on 2022-11-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_download', '0002_document_name_alter_document_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
